public class Future_apex_eg2 
{
    public static void method1()
    {
        system.debug('method1-1');
        system.debug('method1-2');
        system.debug('method1-3');
    }
    public static void method2()
    {
        system.debug('method 2-1');
        system.debug('method 2-2');
        system.debug('method 2-3');
    }
    public static void method3()
    {
     	system.debug('method 3-1');
        system.debug('method 3-2');
        system.debug('method 3-3');   
    }
}