public class IMPLEMENT_INTERFACE_EG2 IMPLEMENTS INTERFACE_CLASS_EG1
{
    PUBLIC void CHATTING()
    {
        system.debug('always 24 hours on to chat with girlfriend');
    }
    PUBLIC void SHOPPING(INTEGER Times)
    {
        times = 100;
        system.debug('unlimited money will spend for girlfriend ' +times);
    }
    public void transporting()
    {
        system.debug('always free to fly any where my girlfriend wants');
    }
}