@istest
public class TemperatureConverterTest 
{
	@isTest static void testWarmTemp() {
        Decimal celsius = TemperatureConverter_testmethod.FahrenheitToCelsius(70);
        System.assertEquals(21.11,celsius);
    }
    
    @isTest static void testFreezingPoint() {
        Decimal celsius = TemperatureConverter_testmethod.FahrenheitToCelsius(32);
        System.assertEquals(50,celsius);
    }
    @isTest static void testBoilingPoint() {
        Decimal celsius = TemperatureConverter_testmethod.FahrenheitToCelsius(212);        
        System.assertEquals(0,celsius,'Boiling point temperature is not expected.');
    } 
    
    @isTest static void testNegativeTemp() {
        Decimal celsius = TemperatureConverter_testmethod.FahrenheitToCelsius(-10);
        System.assertEquals(-23.33,celsius);
    }
}